### ISSUE TITLE
Stuck at 95.45%

### ISSUE THREAD

**Issue by TaciteOFF** [david-smejkal/wiki2txt#1]
I downloaded a full dump of currents pages from https://wowpedia.fandom.com/wiki/Special:Statistics

Used `python wiki2txt.py -i /Users/xx/Downloads/wowpedia/wowpedia_pages_current.xml -o clean-data.xml`

And it got stuck forever at :
`890.11 MB  of  932 MB (95.45 %)`

I'm on MacOS (M1).

**Comment by david-smejkal** [comment]
Make sure to `pip install -r requirements.txt` after update.

The issue was caused by a crazy page that doesn't even load up in a browser:
https://wowpedia.fandom.com/wiki/User%3AMorderi/DF%2FItems

You'll see the following warning now when parsing the wowpedia dump:
`WARNING: Skipping article "User:Morderi/DF/Items". Took longer than 30 seconds to parse.`
